name: stellar_hpv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - pyarrow
  - astropy
  - astroquery
  - tqdm
  - pyyaml
  - h5py
  - pip
  - pip:
      - lightkurve
      - python-dotenv
