import os
import yaml
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

INP = "/mnt/g/STAR_HPV/processed/state_vectors/kepler_led_state_vector_gmmgate.parquet"
TAIL_YAML = "/mnt/g/STAR_HPV/results/anchor_catalogs/kepler_ripe_tail_summary.yaml"

OUT_DIR = "/mnt/g/STAR_HPV/results/figures/ripe_tail"
LATEX_OUT = os.path.join(OUT_DIR, "figures_ripe_tail.tex")

BINS = ["3200-4000", "4000-5200", "5200-6000", "6000-7500"]
TAIL_TAGS = ["q90", "q95"]

def safe_float(x):
    try:
        return float(x)
    except Exception:
        return np.nan

def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    df = pd.read_parquet(INP).copy()
    df["teff_bin_s"] = df["teff_bin_s"].astype(str)
    df["prot_days"] = pd.to_numeric(df["prot_days"], errors="coerce")
    df["Phi_gmm"] = pd.to_numeric(df["Phi_gmm"], errors="coerce")
    df = df.dropna(subset=["prot_days", "Phi_gmm", "teff_bin_s"]).copy()
    df = df[df["prot_days"] > 0].copy()

    with open(TAIL_YAML, "r") as f:
        tail = yaml.safe_load(f)

    # Extract phi thresholds per bin for q90/q95
    phi_thr = {tag: {} for tag in TAIL_TAGS}
    for tag in TAIL_TAGS:
        comp = tail["tails"][tag]["comparison_by_bin"]
        for tb in BINS:
            if tb in comp:
                phi_thr[tag][tb] = safe_float(comp[tb]["phi_threshold"])

    latex_blocks = []
    latex_blocks.append("% Auto-generated by src/24_plot_tail_vs_nontail_period_hist.py")
    latex_blocks.append("% Place this file into your logbook with: \\input{.../figures_ripe_tail.tex}")
    latex_blocks.append("")

    for tag in TAIL_TAGS:
        for tb in BINS:
            thr = phi_thr.get(tag, {}).get(tb, np.nan)
            if not np.isfinite(thr):
                continue

            sub = df[df["teff_bin_s"] == tb].copy()
            if len(sub) < 50:
                continue

            tail_mask = sub["Phi_gmm"] >= thr
            if tail_mask.sum() < 20 or (~tail_mask).sum() < 20:
                continue

            # Prepare data (log scale is often clearer for periods, but keep days for interpretability)
            x_tail = sub.loc[tail_mask, "prot_days"].to_numpy(dtype=float)
            x_non  = sub.loc[~tail_mask, "prot_days"].to_numpy(dtype=float)

            # Common bins for both (in linear days)
            # Robust range: 0.5% to 99.5% of combined
            comb = np.concatenate([x_tail, x_non])
            lo = np.nanquantile(comb, 0.005)
            hi = np.nanquantile(comb, 0.995)
            if not np.isfinite(lo) or not np.isfinite(hi) or hi <= lo:
                continue

            nbins = 30
            bins = np.linspace(lo, hi, nbins + 1)

            fig = plt.figure(figsize=(7.2, 4.6))
            ax = plt.gca()

            # Overlaid histograms, density normalized
            ax.hist(x_non, bins=bins, density=True, alpha=0.55, label=f"Non-tail ({len(x_non)})")
            ax.hist(x_tail, bins=bins, density=True, alpha=0.55, label=f"Ripe tail {tag.upper()} ({len(x_tail)})")

            # Medians
            m_tail = float(np.nanmedian(x_tail))
            m_non = float(np.nanmedian(x_non))
            ax.axvline(m_tail, linewidth=1.5)
            ax.axvline(m_non, linewidth=1.5)

            ax.set_title(f"Kepler GMM post-gate: Prot distributions, {tb} K, tail={tag.upper()}")
            ax.set_xlabel("Rotation period Prot (days)")
            ax.set_ylabel("Density")
            ax.legend(frameon=False)

            fname = f"prot_hist_tail_{tag}_{tb.replace('-','_')}.png"
            out_png = os.path.join(OUT_DIR, fname)
            fig.tight_layout()
            fig.savefig(out_png, dpi=180)
            plt.close(fig)

            # LaTeX placeholder for this panel
            latex_blocks.append("\\begin{figure}[t]")
            latex_blocks.append("\\centering")
            latex_blocks.append(f"\\includegraphics[width=0.95\\linewidth]{{{out_png}}}")
            latex_blocks.append(
                "\\caption{"
                f"Kepler GMM post-gate sample, $T_\\mathrm{{eff}}$ bin {tb} K. "
                f"Overlaid rotation-period distributions for the ripe tail ({tag.upper()}; $\\Phi_\\star\\ge Q_{{{tag[1:]}}}$ within bin) "
                "and the remaining post-gate population. "
                f"Vertical lines indicate medians: $\\tilde{{P}}_\\mathrm{{tail}}={m_tail:.2f}$ d and "
                f"$\\tilde{{P}}_\\mathrm{{non}}={m_non:.2f}$ d. "
                "}"
            )
            latex_blocks.append(f"\\label{{fig:prot_tail_{tag}_{tb.replace('-','_')}}}")
            latex_blocks.append("\\end{figure}")
            latex_blocks.append("")

    with open(LATEX_OUT, "w") as f:
        f.write("\n".join(latex_blocks))

    print("saved figures to:", OUT_DIR)
    print("saved LaTeX snippet:", LATEX_OUT)

if __name__ == "__main__":
    main()
