import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

INP_GMM = "/mnt/g/STAR_HPV/processed/state_vectors/kepler_led_state_vector_gmmgate.parquet"

TAIL_Q90 = "/mnt/g/STAR_HPV/results/anchor_catalogs/kepler_ripe_tail_window_q90.parquet"
TAIL_Q95 = "/mnt/g/STAR_HPV/results/anchor_catalogs/kepler_ripe_tail_window_q95.parquet"

OUT_DIR = "/mnt/g/STAR_HPV/results/figures/ripe_tail_window"
OUT_TEX = f"{OUT_DIR}/figures_ripe_tail_window.tex"

BINS_ORDER = ["3200-4000", "4000-5200", "5200-6000", "6000-7500"]

def norm_sid(s):
    return s.astype("string").str.strip().str.replace(r"\.0$", "", regex=True)

def ensure_dir(p):
    os.makedirs(p, exist_ok=True)

def plot_hist(bin_label, tail_tag, tail_ids, prot_all, out_png):
    # prot_all: Series of window-only prot_days for this teff bin (all window stars)
    # tail_ids: set of source_id for tail in that bin
    df = prot_all.dropna().copy()
    if len(df) == 0:
        return False

    # Split into tail vs rest inside window
    # We need source_id alignment: prot_all is a dataframe slice
    # Here we pass it as a DataFrame
    raise RuntimeError("Internal misuse; call plot_hist_df instead.")

def plot_hist_df(bin_label, tail_tag, df_win_bin, tail_sid_set, out_png):
    # df_win_bin must have columns: source_id, prot_days
    d = df_win_bin.copy()
    d["prot_days"] = pd.to_numeric(d["prot_days"], errors="coerce")
    d = d.dropna(subset=["prot_days"]).copy()
    if len(d) == 0:
        return False

    is_tail = d["source_id"].isin(tail_sid_set)
    tail = d.loc[is_tail, "prot_days"]
    rest = d.loc[~is_tail, "prot_days"]

    if len(tail) < 5:
        # too small to plot meaningfully
        return False

    # Common bins based on pooled range
    lo = float(np.nanmin(d["prot_days"]))
    hi = float(np.nanmax(d["prot_days"]))
    if not np.isfinite(lo) or not np.isfinite(hi) or hi <= lo:
        return False

    nb = 30
    bins = np.linspace(lo, hi, nb + 1)

    plt.figure()
    plt.hist(rest, bins=bins, alpha=0.6, label=f"Window rest (N={len(rest)})")
    plt.hist(tail, bins=bins, alpha=0.6, label=f"{tail_tag} tail (N={len(tail)})")
    plt.xlabel(r"$P_{\rm rot}$ [days]")
    plt.ylabel("Count")
    plt.title(f"{bin_label}: {tail_tag} tail vs window rest")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_png, dpi=200)
    plt.close()
    return True

def main():
    ensure_dir(OUT_DIR)

    # Load GMM gate sample
    g = pd.read_parquet(INP_GMM)
    g["source_id"] = norm_sid(g["source_id"])
    if "in_window_gmm" not in g.columns:
        raise RuntimeError("Missing in_window_gmm in gmmgate parquet.")
    if "teff_bin_s" not in g.columns:
        raise RuntimeError("Missing teff_bin_s in gmmgate parquet.")
    if "prot_days" not in g.columns:
        raise RuntimeError("Missing prot_days in gmmgate parquet.")

    # Window-only cohort (anchor)
    win = g[g["in_window_gmm"].astype(bool)].copy()
    win = win[["source_id", "teff_bin_s", "prot_days"]].copy()

    # Load strict window tails
    t90 = pd.read_parquet(TAIL_Q90, columns=["source_id", "teff_bin_s"])
    t95 = pd.read_parquet(TAIL_Q95, columns=["source_id", "teff_bin_s"])
    t90["source_id"] = norm_sid(t90["source_id"])
    t95["source_id"] = norm_sid(t95["source_id"])

    # Build tail sets per bin
    t90_by = {b: set(t90.loc[t90["teff_bin_s"].astype(str) == b, "source_id"]) for b in BINS_ORDER}
    t95_by = {b: set(t95.loc[t95["teff_bin_s"].astype(str) == b, "source_id"]) for b in BINS_ORDER}

    tex_lines = []
    tex_lines.append(r"% Auto-generated by src/24b_plot_window_tail_vs_window_rest_hist.py")
    tex_lines.append(r"\begin{figure*}[t]")
    tex_lines.append(r"\centering")

    # Make figures for each bin and each tail tag
    figs_made = 0
    for b in BINS_ORDER:
        dfb = win[win["teff_bin_s"].astype(str) == b].copy()
        if len(dfb) == 0:
            continue

        # q90
        out1 = f"{OUT_DIR}/prot_hist_windowtail_q90_{b.replace('-','_')}.png"
        ok1 = plot_hist_df(b, "q90", dfb, t90_by.get(b, set()), out1)
        if ok1:
            figs_made += 1
            tex_lines.append(rf"\includegraphics[width=0.48\textwidth]{{{out1}}}")

        # q95
        out2 = f"{OUT_DIR}/prot_hist_windowtail_q95_{b.replace('-','_')}.png"
        ok2 = plot_hist_df(b, "q95", dfb, t95_by.get(b, set()), out2)
        if ok2:
            figs_made += 1
            tex_lines.append(rf"\includegraphics[width=0.48\textwidth]{{{out2}}}")

        if ok1 or ok2:
            tex_lines.append(r"\vspace{0.2cm}")

    tex_lines.append(r"\caption{Rotation-period distributions comparing strict-window ripe tails (q90 and q95) to the remainder of the homeostatic window, shown per effective-temperature bin.}")
    tex_lines.append(r"\label{fig:ripe_tail_window_prot_hists}")
    tex_lines.append(r"\end{figure*}")
    tex = "\n".join(tex_lines)

    with open(OUT_TEX, "w") as f:
        f.write(tex + "\n")

    print("saved figures to:", OUT_DIR)
    print("saved LaTeX snippet:", OUT_TEX)
    print("figures made:", figs_made)

if __name__ == "__main__":
    main()
