import os
import yaml
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

INP_GMM = "/mnt/g/STAR_HPV/processed/state_vectors/kepler_led_state_vector_gmmgate.parquet"
SUMMARY = "/mnt/g/STAR_HPV/results/anchor_catalogs/kepler_ripe_tail_window_summary.yaml"

OUT_DIR = "/mnt/g/STAR_HPV/results/figures/ripeness_window"
OUT_TEX = f"{OUT_DIR}/figures_ripeness_window.tex"

BINS_ORDER = ["3200-4000", "4000-5200", "5200-6000", "6000-7500"]

def ensure_dir(p):
    os.makedirs(p, exist_ok=True)

def norm_sid(s):
    return s.astype("string").str.strip().str.replace(r"\.0$", "", regex=True)

def main():
    ensure_dir(OUT_DIR)

    with open(SUMMARY, "r") as f:
        sm = yaml.safe_load(f)

    thr90 = float(sm["tails"]["q90"]["ripeness_threshold"])
    thr95 = float(sm["tails"]["q95"]["ripeness_threshold"])

    g = pd.read_parquet(INP_GMM)
    g["source_id"] = norm_sid(g["source_id"])

    need = ["in_window_gmm", "teff_bin_s", "prot_days", "Phi_gmm"]
    miss = [c for c in need if c not in g.columns]
    if miss:
        raise RuntimeError(f"Missing columns in {INP_GMM}: {miss}")

    w = g[g["in_window_gmm"].astype(bool)].copy()
    w["prot_days"] = pd.to_numeric(w["prot_days"], errors="coerce")
    w["Phi_gmm"] = pd.to_numeric(w["Phi_gmm"], errors="coerce")
    w = w.dropna(subset=["prot_days", "Phi_gmm"]).copy()
    w["ripeness_gmm"] = w["prot_days"] * w["Phi_gmm"]

    tex_lines = []
    tex_lines.append(r"% Auto-generated by src/24c_plot_ripeness_distribution_within_window.py")
    tex_lines.append(r"\begin{figure*}[t]")
    tex_lines.append(r"\centering")

    figs_made = 0
    for b in BINS_ORDER:
        dfb = w[w["teff_bin_s"].astype(str) == b].copy()
        if len(dfb) < 20:
            continue

        x = dfb["ripeness_gmm"].astype(float)
        x = x[np.isfinite(x)]

        if len(x) < 20:
            continue

        out_png = f"{OUT_DIR}/ripeness_hist_window_{b.replace('-','_')}.png"

        # bins
        lo = float(np.nanquantile(x, 0.001))
        hi = float(np.nanquantile(x, 0.999))
        if not np.isfinite(lo) or not np.isfinite(hi) or hi <= lo:
            continue

        nb = 40
        bins = np.linspace(lo, hi, nb + 1)

        plt.figure()
        plt.hist(x, bins=bins, alpha=0.8)
        plt.axvline(thr90, linestyle="--", linewidth=2, label=f"overall q90={thr90:.2f}")
        plt.axvline(thr95, linestyle="--", linewidth=2, label=f"overall q95={thr95:.2f}")
        plt.xlabel(r"$R^{\rm ripe}_{\rm gmm}=\Phi_{\rm gmm}\,P_{\rm rot}$")
        plt.ylabel("Count (window only)")
        plt.title(f"{b}: Ripeness distribution inside window (N={len(x)})")
        plt.legend()
        plt.tight_layout()
        plt.savefig(out_png, dpi=200)
        plt.close()

        figs_made += 1
        tex_lines.append(rf"\includegraphics[width=0.48\textwidth]{{{out_png}}}")

    tex_lines.append(r"\caption{Ripeness proxy distributions inside the strict homeostatic window, per temperature bin. Vertical lines mark the overall strict-window thresholds used to define the q90 and q95 window-tails.}")
    tex_lines.append(r"\label{fig:ripeness_window_distributions}")
    tex_lines.append(r"\end{figure*}")

    with open(OUT_TEX, "w") as f:
        f.write("\n".join(tex_lines) + "\n")

    print("saved figures to:", OUT_DIR)
    print("saved LaTeX snippet:", OUT_TEX)
    print("figures made:", figs_made)

if __name__ == "__main__":
    main()
