#!/usr/bin/env python3
"""
src/45c2_variance_scaling_shv_rotation_smoothing_capped.py

Rotation-scale coarse-graining (capped windows).

Key change vs 45c:
- window size derived from bandwidth h is capped to max_window_frac * N_bin
  so the smoother cannot collapse into a global median for moderate h.

Outputs:
  /mnt/g/STAR_HPV/results/variance_scaling/variance_scaling_rotation_smoothing_capped.csv
  /mnt/g/STAR_HPV/results/variance_scaling/variance_scaling_rotation_smoothing_capped.yaml
  /mnt/g/STAR_HPV/results/figures/variance_scaling_rotation_smoothing_capped/*.png
  /mnt/g/STAR_HPV/results/figures/variance_scaling_rotation_smoothing_capped/figures_variance_scaling_rotation_smoothing_capped.tex
"""

from __future__ import annotations

import os
import argparse
from dataclasses import dataclass
from typing import Dict, List

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yaml


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)

def safe_var(x: np.ndarray) -> float:
    x = x[np.isfinite(x)]
    if x.size < 2:
        return np.nan
    return float(np.var(x, ddof=1))

def mad(x: np.ndarray) -> float:
    x = x[np.isfinite(x)]
    if x.size == 0:
        return np.nan
    med = np.median(x)
    return float(np.median(np.abs(x - med)))

def robust_var_mad2(x: np.ndarray) -> float:
    m = mad(x)
    return float(m * m) if np.isfinite(m) else np.nan

def rolling_median_on_sorted(x: np.ndarray, y: np.ndarray, w: int) -> np.ndarray:
    n = len(x)
    if n == 0:
        return np.array([])
    if w < 3:
        return y.copy()
    if w % 2 == 0:
        w += 1
    w = min(w, n if n % 2 == 1 else n - 1)
    if w < 3:
        return y.copy()

    order = np.argsort(x)
    y_s = y[order]
    half = w // 2

    y_sm = np.empty_like(y_s, dtype=float)
    for i in range(n):
        lo = max(0, i - half)
        hi = min(n, i + half + 1)
        window = y_s[lo:hi]
        window = window[np.isfinite(window)]
        y_sm[i] = np.median(window) if window.size else np.nan

    out = np.empty_like(y, dtype=float)
    out[order] = y_sm
    return out

def estimate_window_size_from_bandwidth(logp: np.ndarray, h: float, w_min: int = 21) -> int:
    lp = logp[np.isfinite(logp)]
    if lp.size < 50:
        return w_min
    s = np.sort(lp)
    d = np.diff(s)
    d = d[np.isfinite(d) & (d > 0)]
    if d.size == 0:
        return w_min
    spacing = float(np.median(d))
    if spacing <= 0:
        return w_min
    w = int(max(w_min, round((2.0 * h) / spacing)))
    if w % 2 == 0:
        w += 1
    return w


@dataclass
class RotScaleResult:
    teff_bin_s: str
    h_logp: float
    window_size: int
    n: int
    var_resid: float
    mad2_resid: float


def compute_rotation_smoothing_capped(
    df: pd.DataFrame,
    teff_col: str,
    logp_col: str,
    phi_col: str,
    h_list: List[float],
    min_n: int,
    max_window_frac: float,
    w_min: int = 21,
) -> List[RotScaleResult]:
    out: List[RotScaleResult] = []

    for teff_bin, g in df.groupby(teff_col):
        g = g[[logp_col, phi_col]].copy().dropna(subset=[logp_col, phi_col])
        nbin = int(g.shape[0])
        if nbin < min_n:
            continue

        logp = g[logp_col].to_numpy(dtype=float)
        phi = g[phi_col].to_numpy(dtype=float)

        # Cap relative to this teff bin
        cap = int(max(w_min, round(max_window_frac * nbin)))
        if cap % 2 == 0:
            cap += 1
        cap = min(cap, nbin if nbin % 2 == 1 else nbin - 1)

        for h in h_list:
            w_est = estimate_window_size_from_bandwidth(logp, h=h, w_min=w_min)
            w = min(w_est, cap)
            if w % 2 == 0:
                w += 1
            w = min(w, nbin if nbin % 2 == 1 else nbin - 1)

            phi_hat = rolling_median_on_sorted(logp, phi, w=w)
            resid = phi - phi_hat

            out.append(
                RotScaleResult(
                    teff_bin_s=str(teff_bin),
                    h_logp=float(h),
                    window_size=int(w),
                    n=int(np.sum(np.isfinite(resid))),
                    var_resid=safe_var(resid),
                    mad2_resid=robust_var_mad2(resid),
                )
            )

    return out


def pooled_curve(df_res: pd.DataFrame, ycol: str) -> pd.DataFrame:
    return (
        df_res.groupby("h_logp")
        .agg(y=(ycol, "mean"), w=("window_size", "mean"))
        .reset_index()
        .sort_values("h_logp")
    )


def write_tex_snippet(tex_path: str, fig_paths: Dict[str, str]) -> None:
    lines = []
    lines.append(r"% Auto-generated by src/45c2_variance_scaling_shv_rotation_smoothing_capped.py")
    for key, path in fig_paths.items():
        label = f"fig:variance_scaling_rotation_capped:{key}"
        caption = key.replace("_", " ")
        lines.append(r"\begin{figure}[t]")
        lines.append(r"  \centering")
        lines.append(rf"  \includegraphics[width=0.92\linewidth]{{{path}}}")
        lines.append(rf"  \caption{{{caption}.}}")
        lines.append(rf"  \label{{{label}}}")
        lines.append(r"\end{figure}")
        lines.append("")
    with open(tex_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).strip() + "\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="/mnt/g/STAR_HPV/processed/gyro/kepler_gmmgate_with_gyro_ages_mamajek.parquet")
    ap.add_argument("--outdir", default="/mnt/g/STAR_HPV/results/variance_scaling")
    ap.add_argument("--figdir", default="/mnt/g/STAR_HPV/results/figures/variance_scaling_rotation_smoothing_capped")
    ap.add_argument("--teff-col", default="teff_bin_s")
    ap.add_argument("--prot-col", default="prot_days")
    ap.add_argument("--phi-col", default="Phi_gmm")
    ap.add_argument("--h-list", default="0.05,0.10,0.20,0.30,0.50")
    ap.add_argument("--min-n", type=int, default=200)
    ap.add_argument("--max-window-frac", type=float, default=0.35,
                    help="Cap rolling window to this fraction of N within each teff bin.")
    ap.add_argument("--seed", type=int, default=123)
    args = ap.parse_args()

    ensure_dir(args.outdir)
    ensure_dir(args.figdir)

    h_list = [float(x.strip()) for x in args.h_list.split(",") if x.strip()]
    rng = np.random.default_rng(args.seed)

    df = pd.read_parquet(args.input).copy()

    # Resolve rotation period column
    prot_col = args.prot_col
    if prot_col not in df.columns:
        if "gate_days_gmm" in df.columns:
            prot_col = "gate_days_gmm"
        else:
            raise SystemExit(f"prot column '{args.prot_col}' not found and gate_days_gmm not found.")

    needed = [args.teff_col, prot_col, args.phi_col]
    missing = [c for c in needed if c not in df.columns]
    if missing:
        raise SystemExit(f"Missing columns in input parquet: {missing}")

    df = df.dropna(subset=[args.teff_col, prot_col, args.phi_col]).copy()
    df["logP"] = np.log10(df[prot_col].to_numpy(dtype=float))

    # Observed
    obs = compute_rotation_smoothing_capped(
        df=df,
        teff_col=args.teff_col,
        logp_col="logP",
        phi_col=args.phi_col,
        h_list=h_list,
        min_n=args.min_n,
        max_window_frac=args.max_window_frac,
    )
    obs_df = pd.DataFrame([r.__dict__ for r in obs])
    obs_df["variant"] = "observed"

    # Null
    df_null = df[[args.teff_col, "logP", args.phi_col]].copy()

    def permute_within_group(s: pd.Series) -> pd.Series:
        arr = s.to_numpy()
        perm = rng.permutation(arr)
        return pd.Series(perm, index=s.index)

    df_null["Phi_perm"] = df_null.groupby(args.teff_col)[args.phi_col].transform(permute_within_group)

    null = compute_rotation_smoothing_capped(
        df=df_null.rename(columns={"Phi_perm": args.phi_col}),
        teff_col=args.teff_col,
        logp_col="logP",
        phi_col=args.phi_col,
        h_list=h_list,
        min_n=args.min_n,
        max_window_frac=args.max_window_frac,
    )
    null_df = pd.DataFrame([r.__dict__ for r in null])
    null_df["variant"] = "permute_phi_within_teff"

    out = pd.concat([obs_df, null_df], ignore_index=True)

    out_csv = os.path.join(args.outdir, "variance_scaling_rotation_smoothing_capped.csv")
    out_yaml = os.path.join(args.outdir, "variance_scaling_rotation_smoothing_capped.yaml")
    out.to_csv(out_csv, index=False)

    meta = {
        "input": args.input,
        "prot_col_used": prot_col,
        "h_list": h_list,
        "min_n": args.min_n,
        "max_window_frac": args.max_window_frac,
        "seed": args.seed,
        "n_rows_loaded": int(len(df)),
        "outputs": {"csv": out_csv},
        "figdir": args.figdir,
    }
    with open(out_yaml, "w", encoding="utf-8") as f:
        yaml.safe_dump(meta, f, sort_keys=False)

    # Figures (pooled)
    fig_paths: Dict[str, str] = {}
    for ycol in ["var_resid", "mad2_resid"]:
        p_obs = pooled_curve(out[out["variant"] == "observed"], ycol=ycol)
        p_null = pooled_curve(out[out["variant"] == "permute_phi_within_teff"], ycol=ycol)

        plt.figure()
        if not p_obs.empty:
            plt.plot(p_obs["h_logp"], p_obs["y"], marker="o", linestyle="-", label="observed (pooled)")
        if not p_null.empty:
            plt.plot(p_null["h_logp"], p_null["y"], marker="s", linestyle="--", label="null (pooled)")
        plt.xlabel("smoothing bandwidth h in log10(P_rot)")
        plt.ylabel(ycol)
        plt.title(f"Rotation-scale coarse graining (capped): {ycol} vs h | max_window_frac={args.max_window_frac}")
        plt.legend(fontsize=9)
        plt.tight_layout()
        out_png = os.path.join(args.figdir, f"pooled_rotation_smoothing_capped_{ycol}.png")
        plt.savefig(out_png, dpi=200)
        plt.close()
        fig_paths[f"pooled_rotation_smoothing_capped_{ycol}"] = out_png

    tex_path = os.path.join(args.figdir, "figures_variance_scaling_rotation_smoothing_capped.tex")
    write_tex_snippet(tex_path, fig_paths)

    print(f"[OK] wrote {out_csv}")
    print(f"[OK] wrote {out_yaml}")
    print(f"[OK] wrote figures to {args.figdir}")
    print(f"[OK] wrote TeX snippet {tex_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
